name: wiseft_5090
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.11.4
  - expat=2.7.3
  - ld_impl_linux-64=2.44
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - libnsl=2.0.0
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.0.18
  - pip=25.3
  - pthread-stubs=0.3
  - python=3.10.19
  - readline=8.3
  - setuptools=80.9.0
  - sqlite=3.51.0
  - tk=8.6.15
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - absl-py==2.3.1
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - clip==1.0
      - contourpy==1.3.2
      - cuda-bindings==13.0.3
      - cuda-pathfinder==1.2.2
      - cycler==0.12.1
      - filelock==3.19.1
      - fonttools==4.61.0
      - fsspec==2025.9.0
      - ftfy==6.3.1
      - grpcio==1.76.0
      - idna==3.11
      - imagenetv2-pytorch==0.1
      - jinja2==3.1.6
      - joblib==1.5.2
      - kiwisolver==1.4.9
      - littleutils==0.2.4
      - markdown==3.10
      - markupsafe==2.1.5
      - matplotlib==3.10.7
      - mpmath==1.3.0
      - networkx==3.3
      - numpy==2.1.2
      - nvidia-cublas==13.1.0.3
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti==13.0.85
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc==13.0.88
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime==13.0.96
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cudnn-cu13==9.13.0.50
      - nvidia-cufft==12.0.0.61
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-cufile==1.15.1.6
      - nvidia-curand==10.4.0.35
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver==12.0.4.66
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse==12.6.3.3
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-cusparselt-cu13==0.8.0
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nccl-cu13==2.27.7
      - nvidia-nvjitlink==13.0.88
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvshmem-cu13==3.4.5
      - nvidia-nvtx==13.0.85
      - nvidia-nvtx-cu12==12.4.127
      - ogb==1.3.6
      - outdated==0.2.2
      - packaging==25.0
      - pandas==2.3.3
      - pillow==11.3.0
      - protobuf==6.33.1
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - pytorch-triton==3.5.1+gitbfeb0668
      - pytz==2025.2
      - pyyaml==6.0.3
      - regex==2025.11.3
      - requests==2.32.5
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - six==1.17.0
      - sympy==1.14.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.6.0
      - torch==2.10.0.dev20251123+cu130
      - torchaudio==2.10.0.dev20251124+cu130
      - torchvision==0.25.0.dev20251124+cu130
      - tqdm==4.67.1
      - triton==3.2.0
      - typing-extensions==4.15.0
      - tzdata==2025.2
      - urllib3==2.5.0
      - wcwidth==0.2.14
      - werkzeug==3.1.4
      - wilds==2.0.0
prefix: /root/miniconda3/envs/wiseft_5090
